### PR TITLE
Fix #46: undefined method `+' for nil:NilClass

### LINKED ISSUE #46: undefined method `+' for nil:NilClass
I have a message that cannot be saved. A minimal example that reproduces the error looks like the log output below:

```
W, [2018-03-18T22:10:59.768498 #12612]  WARN -- : [Folder/Subfolder] failed to save message 318:
Delivered-To: me@example.com
From: example <www.example.com>
To: FirstName LastName <me@example.com>
Subject: Re: no subject
. undefined method `+' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by a-krebs**
Unit tests and fix #46.

### CODE REVIEW

**Comment by joeyates** [comment]
Thanks for the pull request. The fix looks good.

I'd like to change the test, though: instead of asserting there's no failure, could you test for the outcome in the two cases?

**Comment by a-krebs** [comment]
> instead of asserting there's no failure, could you test for the outcome in the two cases?

Good suggestion, I'll do that

**Comment by a-krebs** [comment]
@joeyates I updated this pull request with the changes you suggested

**Comment by joeyates** [comment]
@a-krebs Thanks for the change.

Could you rebase your branch on the current master?

There are two things I'd like to resolve before merging:

1. there is a conflict between master and this branch,
2. this branch has a merge commit `Merge branch 'master' into feature/46_plus_for_nil_class` - which I'd like to avoid.

```shell
$ git checkout feature/46_plus_for_nil_class
$ git reset --hard 5cfd10a # drop the merge
$ git rebase 3db2b9e # rebase on current master
```

Resolve the resulting conflict in `lib/email/mboxrd/message.rb`:

Conflict:

```ruby
      def from
++<<<<<<< 50779e0bc0d6df0125f98db7f6549a0a74cb468a
 +      parsed.from[0] + " " + asctime
++||||||| merged common ancestors
++      parsed.from[0] + ' ' + asctime
++=======
+       best_from + ' ' + asctime
++>>>>>>> Choose 'from' field from available headers.
      end
```

Resolution:

```ruby
    def from
      best_from + "" + asctime
    end
```

```shell
$ git add lib/email/mboxrd/message.rb
$ git rebasse --continue
$ git push --force
```

**Comment by joeyates** [comment]
Merged, thanks!

**Pull request merged**
